fos_rest:
    view:
        view_response_listener: true
    body_listener:
        enabled: true
    format_listener:
        rules:
            - { host: api.artpeintre.fr, path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json] }
            - { host: artpeintre.fr, path: ^/, priorities: [ html ] , fallback_format: html }